image: atlassian/default-image:2

pipelines:
  default:
    - step:
        script:
          - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
          - docker build -t $DOCKER_HUB_USER/ubuntu-sshd:latest .
          - docker push $DOCKER_HUB_USER/ubuntu-sshd:latest
        services:
          - docker
        caches:
          - docker
